name: Run Pull Request Tests

on:
  pull_request:
    branches: [master]

jobs:
  unit_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with: { node-version: '14', registry-url: 'https://discovery.jfrog.io/discovery/api/npm/npm/' }
      - env: { NODE_AUTH_TOKEN: "${{ secrets.JFROG_NPM_PUBLISH_AUTH }}" }
        run: npm ci
      - run: npm run lint
      - run: npm run test:coverage